name: shell commands

on: 
  push: # Triggers the workflow on any push event

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: String command
        run: echo "Welcome to DevOps" 

      - name: Multiline script
        run: | 
          node -v # Check Node.js version
          npm -v  # Check npm version
      - name: python command
        run: |
          import platform
          print(platform.processor)
        shell: python
        
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directort PowerShell
        run: Get-Location
      - name: Directort Bash
        run: pwd
        shell: bash



